// Code generated by sqlc. DO NOT EDIT.

package pgdb

import (
	"database/sql"
)

type Improvement struct {
	ID          int32
	Name        sql.NullString
	Description sql.NullString
	StateCode   sql.NullString
	LivingArea  sql.NullString
	Value       sql.NullInt32
	PropertyID  sql.NullInt32
}

type ImprovementDetail struct {
	ID              int32
	ImprovementID   sql.NullInt32
	ImprovementType sql.NullString
	Description     sql.NullString
	Class           sql.NullString
	ExteriorWall    sql.NullString
	YearBuilt       sql.NullInt32
	SquareFeet      sql.NullInt32
}

type Jurisdiction struct {
	ID             int32
	Entity         sql.NullString
	Description    sql.NullString
	TaxRate        sql.NullInt32
	AppraisedValue sql.NullInt32
	TaxableValue   sql.NullInt32
	EstimatedTax   sql.NullInt32
	PropertyID     sql.NullInt32
}

type Land struct {
	ID          int32
	Number      sql.NullInt32
	LandType    sql.NullString
	Description sql.NullString
	Acres       sql.NullFloat64
	SquareFeet  sql.NullFloat64
	EffFront    sql.NullFloat64
	EffDepth    sql.NullFloat64
	MarketValue sql.NullInt32
	PropertyID  sql.NullInt32
}

type Property struct {
	ID                  int32
	OwnerID             sql.NullInt32
	OwnerName           sql.NullString
	OwnerMailingAddress sql.NullString
	Zoning              sql.NullString
	NeighborhoodCd      sql.NullString
	Neighborhood        sql.NullString
	Address             sql.NullString
	LegalDescription    sql.NullString
	GeographicID        sql.NullString
	Exemptions          sql.NullString
	OwnershipPercentage sql.NullString
	MapscoMapID         sql.NullString
	Longitude           sql.NullString
	Latitude            sql.NullString
	AddressNumber       string
	AddressLineTwo      sql.NullString
	City                sql.NullString
	Street              sql.NullString
	County              sql.NullString
	State               sql.NullString
}

type Proxy struct {
	Ip       string
	Lastused sql.NullString
	Uses     sql.NullInt32
	IsBad    sql.NullInt32
}

type RollValue struct {
	ID           int32
	Year         sql.NullInt32
	Improvements sql.NullInt32
	LandMarket   sql.NullInt32
	AgValuation  sql.NullInt32
	Appraised    sql.NullInt32
	HomesteadCap sql.NullInt32
	Assessed     sql.NullInt32
	PropertyID   sql.NullInt32
}
